# Generated by Django 3.0.5 on 2020-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='授权令牌')),
            ],
        ),
    ]
