# Generated by Django 3.0.5 on 2020-05-11 07:52

from django.db import migrations, models
import lib.orm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=8)),
                ('dating_city', models.CharField(default='北京', max_length=32, verbose_name='目标城市')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小约会年龄')),
                ('max_dating_age', models.IntegerField(default=49, verbose_name='最大约会年龄')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小约会距离')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大约会距离')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_match', models.BooleanField(default=True, verbose_name='是否好友可见')),
                ('auto_play', models.BooleanField(default=True, verbose_name='是否自动播放')),
            ],
            bases=(models.Model, lib.orm.ModelMixin),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, null=True, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=32, null=True, unique=True, verbose_name='昵称')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='授权令牌')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=8)),
                ('avatar', models.CharField(max_length=256, null=True)),
                ('location', models.CharField(default='北京', max_length=32)),
                ('birth_year', models.IntegerField(default=2000)),
                ('birth_month', models.IntegerField(default=1)),
                ('birth_day', models.IntegerField(default=1)),
                ('vip_id', models.IntegerField(default=0)),
            ],
        ),
    ]
