# Generated by Django 3.0.5 on 2020-04-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=8)),
                ('dating_city', models.CharField(default='北京', max_length=32, verbose_name='目标城市')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小约会年龄')),
                ('max_dating_age', models.IntegerField(default=49, verbose_name='最大约会年龄')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小约会距离')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大约会距离')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_match', models.BooleanField(default=True, verbose_name='是否好友可见')),
                ('auto_play', models.BooleanField(default=True, verbose_name='是否自动播放')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='北京', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='昵称'),
        ),
    ]
